-- MySQL Script generated by MySQL Workbench
-- Sun Apr  6 11:16:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `year_birth` DATE NULL,
  `direction` VARCHAR(255) NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Phone` (
  `phone_id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(255) NULL,
  PRIMARY KEY (`phone_id`, `number`),
  CONSTRAINT `FK_phone`
    FOREIGN KEY (`phone_id`)
    REFERENCES `mydb`.`Person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `date_end_relation` DATE NULL,
  PRIMARY KEY (`person_id`),
  CONSTRAINT `FK_person-customer`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`Person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seller` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `nss` VARCHAR(255) NULL,
  `salary` DECIMAL(10,2) NULL,
  `kind_contract` ENUM('comercial', 'api') NULL,
  PRIMARY KEY (`person_id`),
  CONSTRAINT `FK_person_seller`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`Person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owner` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `nif` VARCHAR(255) NULL,
  PRIMARY KEY (`person_id`),
  CONSTRAINT `FK_person_owner`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`Person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Api`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Api` (
  `api_id` VARCHAR(45) NOT NULL,
  `record_number` VARCHAR(255) NULL,
  `record_date` DATE NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`api_id`),
  INDEX `fk_Api_Seller1_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `fk_Api_Seller1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `mydb`.`Seller` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flat` (
  `flat_id` INT NOT NULL,
  `direction` VARCHAR(255) NULL,
  `surface` DECIMAL(3,2) NULL,
  `num_rooms` TINYINT NULL,
  `price` DECIMAL(9,2) NULL,
  `zone_id` INT NULL,
  PRIMARY KEY (`flat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visit` (
  `visiti_id` INT NOT NULL,
  `date` DATE NULL,
  `hour` TIME NULL,
  `customer_id` INT NOT NULL,
  `flat_id` INT NOT NULL,
  PRIMARY KEY (`visiti_id`),
  INDEX `KF_customer_idx` (`customer_id` ASC) VISIBLE,
  INDEX `FK_flat_idx` (`flat_id` ASC) VISIBLE,
  CONSTRAINT `KF_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customer` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_flat`
    FOREIGN KEY (`flat_id`)
    REFERENCES `mydb`.`Flat` (`flat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Characteristics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Characteristics` (
  `id` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Satisfaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Satisfaction` (
  `characteristics_id` INT NOT NULL,
  `flat_id` INT NOT NULL,
  `no_satisfaction` ENUM('yes', 'no') NULL,
  PRIMARY KEY (`characteristics_id`, `flat_id`),
  INDEX `FK_flat_idx` (`flat_id` ASC) VISIBLE,
  CONSTRAINT `FK_characteristics`
    FOREIGN KEY (`characteristics_id`)
    REFERENCES `mydb`.`Characteristics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_flat`
    FOREIGN KEY (`flat_id`)
    REFERENCES `mydb`.`Flat` (`flat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Property` (
  `owner_id` INT NOT NULL,
  `flat_id` INT NOT NULL,
  PRIMARY KEY (`owner_id`, `flat_id`),
  INDEX `FK_flat_idx` (`flat_id` ASC) VISIBLE,
  CONSTRAINT `FK_owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`Owner` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_flat`
    FOREIGN KEY (`flat_id`)
    REFERENCES `mydb`.`Flat` (`flat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Population`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Population` (
  `population_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `num_habitantes` INT NULL,
  PRIMARY KEY (`population_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zone` (
  `population_id` INT NOT NULL,
  `disc` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`population_id`, `disc`),
  CONSTRAINT `FK_population`
    FOREIGN KEY (`population_id` , `disc`)
    REFERENCES `mydb`.`Population` (`population_id` , `population_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Preference` (
  `customer_id` INT NOT NULL,
  `population_id` INT NOT NULL,
  `disc` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `population_id`, `disc`),
  INDEX `FK_idx` (`population_id` ASC, `disc` ASC) VISIBLE,
  CONSTRAINT `FK_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customer` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_zone`
    FOREIGN KEY (`population_id` , `disc`)
    REFERENCES `mydb`.`Zone` (`population_id` , `disc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bordering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bordering` (
  `covers` INT NOT NULL,
  `covered` INT NOT NULL,
  PRIMARY KEY (`covers`, `covered`),
  CONSTRAINT `FK_covers`
    FOREIGN KEY (`covers`)
    REFERENCES `mydb`.`Zone` (`population_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_covered`
    FOREIGN KEY (`covers` , `covered`)
    REFERENCES `mydb`.`Zone` (`population_id` , `population_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
